import type { Metadata } from "next";
import "./globals.css";
import { dark } from '@clerk/themes';
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{baseTheme:dark}}>
      <head><meta name="google-site-verification" content="ptOorYGu0Y3qXA4PMGGc5oYbgBjv4wj8RZTmZNFZ1TY" /></head>
      <html lang="en">
        <body>
          
          <ThemeProvider
              attribute="class"
              forcedTheme="dark"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Toaster theme="light"
                position="bottom-right"/>
              {children}
            </ThemeProvider>
          </body>
      </html>     
    </ClerkProvider>
  );
}
